Observer: Patrycja

# EEG
Ophthalmic_procedure: False
Send_EEG_trigg: True

# view parameters
Screen_color: 000000
Text_size: 30
Figure_size: 80

# times
Fixation_show_time: [0.5, 0.5]
Cue_show_time: [1, 2]
Target_show_time: [1, 1]
Empty_screen_show_time: [1, 1]
Feedback_show_time: [1, 1]

# reaction keys
Keys: [space]

# experiment structure
Experiment_blocks: [
    {type: training, number_of_go_trials: 10, number_of_shape_trials: 10, number_of_color_trials: 10},
    {type: break, file_name: end_training.txt},
    {type: calibration, number_of_go_trials: 20, number_of_shape_trials: 4, number_of_color_trials: 4},
    {type: break, file_name: end_calibration1.txt},
    {type: experiment, number_of_go_trials: 56, number_of_shape_trials: 14, number_of_color_trials: 14, cutoff: 0.1},
    {type: break, file_name: break1.txt},
    {type: experiment, number_of_go_trials: 56, number_of_shape_trials: 14, number_of_color_trials: 14, cutoff: 0.1},
    {type: break, file_name: break2.txt},
    {type: calibration, number_of_go_trials: 20, number_of_shape_trials: 4, number_of_color_trials: 4},
    {type: break, file_name: end_calibration2.txt},
    {type: experiment, number_of_go_trials: 56, number_of_shape_trials: 14, number_of_color_trials: 14, cutoff: 0.1},
    {type: break, file_name: break3.txt},
    {type: experiment, number_of_go_trials: 56, number_of_shape_trials: 14, number_of_color_trials: 14, cutoff: 0.2},
    {type: break, file_name: end.txt}]

# show feedback
Feedback_go_positive_show: True
Feedback_go_negative_show: True
Feedback_shape_positive_show: False
Feedback_shape_negative_show: False
Feedback_color_positive_show: False
Feedback_color_negative_show: False

# feedback text
Feedback_go_positive_text: ŚWIETNIE!
Feedback_go_negative_text: ZA WOLNO!
Feedback_shape_positive_text: Feedback_shape_positives
Feedback_shape_negative_text: Feedback_shape_negatives
Feedback_color_positive_text: Feedback_color_positives
Feedback_color_negative_text: Feedback_color_negatives

